### ISSUE TITLE
How do you initialised Query2 with the weight of QueryInst?

### ISSUE THREAD

**Issue by JACOBWHY** [howardchina/query2#1]
How do you initialised Query2 with the weight of QueryInst[29] pretrained on the COCO dataset and then fine-tuned on GIST512-DB?

**Comment by howardchina** [comment]
You can check this line:
https://github.com/howardchina/query2/blob/9165cb565dd579ff153c0ca988ec7779df87f34d/configs/ultra_sound/queryglob/queryglob_usdanno514raw_B_2_4_split0.py#L93C1-L93C1
